"""
plot_figS6.py
-------------
Supplementary Figure S6: Spatial Analysis Extended.

Panels:
  A  Metabolic microregion maps (Brain, Kidney, Liver, Lung)
  B  Within-tissue spatial coherence per organ (violin over all samples)
  C  PCA / UMAP scatter coloured by organ (patch-level embeddings)

Usage:
  conda run -n torch_gpu python plot_figS6.py
"""

from __future__ import annotations
from pathlib import Path

from metabofm_paths import METABOFM_ROOT, MSI_RAW_DIR
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize as sk_normalize
from plot_utils import set_nature_style
set_nature_style()

# -- CONFIG -------------------------------------------------------------------
PATCH_DIR = METABOFM_ROOT / "outputs/spatial_patches"
EMB_DIR   = METABOFM_ROOT / "outputs/embeddings_v2"
DATA_ROOT = MSI_RAW_DIR
COLOC_DIR = METABOFM_ROOT / "outputs/channel_colocalization"
OUT_DIR   = METABOFM_ROOT / "outputs/figures"
PANEL_DIR = OUT_DIR / "figS6_spatial_extended"
PANEL_DIR.mkdir(parents=True, exist_ok=True)

DPI        = 300
N_REGIONS  = 6
RNG_SEED   = 42

# Highest-contiguity sample per organ (index into resnet_patch_meta.csv / patch_embeddings)
# Selected by top contiguity score from spatial_coherence_all_samples.csv
BEST_SAMPLES = {
    "Brain":  {"sample_idx": 121,  "npz": "2024-12-10_04h23m56s_r0_c0_C10.npz", "contiguity": 0.849},
    "Kidney": {"sample_idx": 5586, "npz": "2025-10-24_17h07m48s_r0_c0_C8.npz",  "contiguity": 0.836},
    "Lung":   {"sample_idx": 1415, "npz": "2023-02-21_22h30m22s_r0_c0_C32.npz", "contiguity": 0.879},
    "Liver":  {"sample_idx": 4761, "npz": "2023-08-01_19h02m02s_r0_c0_C31.npz", "contiguity": 0.827},
}
ORGANS_A = ["Brain", "Kidney", "Lung", "Liver"]

# Distinct region colours (not too saturated, colourblind-tolerant)
REGION_COLORS = ["#2166ac", "#d6604d", "#4dac26", "#fdae6b", "#9970ab", "#74add1"]

ORGAN_PALETTE = {
    "Brain":  "#2166ac",
    "Kidney": "#d6604d",
    "Liver":  "#4dac26",
    "Lung":   "#fdae6b",
    "Gut":    "#9970ab",
}
DEFAULT_COLOR = "#aaaaaa"


CAPTION = """\
Supplementary Figure 6 | Extended spatial analysis of Stage 1 patch embeddings.

a, Raw MSI mean-intensity projections (left column, viridis scale) and unsupervised metabolic microregion maps (right column) for the highest-contiguity sample in each of four organs. Microregion maps are generated by k-means clustering (k = 6) of Stage 1 patch embeddings projected back onto the spatial grid. Samples are selected as the highest spatial-contiguity example per organ (Brain contiguity = 0.849, Kidney = 0.836, Lung = 0.879, Liver = 0.827). Spatially coherent regions visible in the raw MSI are recapitulated in the cluster map, confirming that Stage 1 captures local metabolic structure.

b, Within-tissue spatial coherence (contiguity score) across organs with >=10 samples. The contiguity score measures the fraction of spatially adjacent patch pairs whose Stage 1 embeddings cluster to the same microregion label. Violin plots show the distribution over individual samples; organs such as Kidney and Lung show clear spatial structure. Results demonstrate that local metabolic neighbourhoods in the tissue section are captured by Stage 1.

c, PCA and UMAP projections of Stage 1 patch-level embeddings coloured by organ type, illustrating tissue-level separation achievable at the pixel level without any sample-level aggregation.

d, Distribution across all 5,600 MSI samples of the Pearson correlation between patch embedding PC1 and spatial row position, PC1 and spatial column position, and their combined mean, quantifying the extent to which the leading embedding axis is aligned with the physical layout of the tissue section (row: mean = 0.237, sigma = 0.143; column: mean = 0.171, sigma = 0.129; combined: mean = 0.204, sigma = 0.086).

e, Per-sample Spearman correlation between pairwise channel-embedding cosine similarity and pairwise spatial colocalization (Pearson correlation of raw ion images) across 399 MSI samples, for Stage 2 channel-refined, Stage 1, and m/z-only embeddings. Stage 1 achieves the highest median colocalization-predictive correlation (mean rho = 0.055), exceeding the m/z-only baseline (mean rho = 0.013), indicating that learned spatial image features carry colocalization information beyond what mass alone provides.
"""

def write_caption():
    (PANEL_DIR / "captions.txt").write_text(CAPTION, encoding="utf-8")
    print("  saved captions.txt")


def save_panel(fig, stem):
    for ax in fig.get_axes():
        ax.set_title("")
    fig.suptitle("")
    fig.savefig(str(PANEL_DIR / f"{stem}.svg"), bbox_inches="tight", pad_inches=0)
    print(f"  saved panel {stem}.svg")


IMG_SIZE = 224   # must match extract_stage1_patch_embeddings.py

def _load_sample(organ: str):
    """Return (raw_msi_mean 224×224, cluster_map 28×28) for the best sample of organ.

    Both outputs share the same spatial layout: the raw MSI is resized to the
    same 224×224 square the model received, so each cluster-map pixel covers
    exactly one 8×8 block in the resized image.
    """
    from PIL import Image
    info = BEST_SAMPLES[organ]
    idx  = info["sample_idx"]

    # Raw MSI — mean across channels, resized to 224×224 (same as model input)
    npz_path = DATA_ROOT / info["npz"]
    d        = np.load(str(npz_path))
    raw      = d["patch"].astype(np.float32)           # (C, H, W)
    raw_mean = raw.mean(axis=0)                        # (H, W) natural resolution
    lo, hi   = np.percentile(raw_mean[raw_mean > 0], [1, 99]) if raw_mean.max() > 0 else (0, 1)
    raw_norm = np.clip((raw_mean - lo) / max(hi - lo, 1e-6), 0, 1)
    # Resize to 224×224 — exactly what the encoder received
    raw_224  = np.array(Image.fromarray((raw_norm * 255).astype(np.uint8))
                        .resize((IMG_SIZE, IMG_SIZE), Image.NEAREST),
                        dtype=np.float32) / 255.0

    # Patch embeddings for this sample: (28, 28, 256)
    emb_all  = np.load(str(EMB_DIR / "resnet_patch_embeddings.npy"),
                       mmap_mode="r")
    emb_samp = emb_all[idx].astype(np.float32)        # (28, 28, 256)
    H_p, W_p = emb_samp.shape[:2]
    flat     = sk_normalize(emb_samp.reshape(-1, emb_samp.shape[-1]), norm="l2")

    km     = KMeans(n_clusters=N_REGIONS, random_state=RNG_SEED, n_init=10)
    labels = km.fit_predict(flat).reshape(H_p, W_p)   # (28, 28)

    return raw_224, labels


def draw_panel_a(axes_grid):
    """2-row × 4-col grid: row 0 = raw MSI, row 1 = microregion map, one col per organ."""
    cmap_region = mcolors.ListedColormap(REGION_COLORS[:N_REGIONS])

    for col, organ in enumerate(ORGANS_A):
        raw_norm, labels = _load_sample(organ)
        info = BEST_SAMPLES[organ]

        ax_raw = axes_grid[0, col]
        ax_map = axes_grid[1, col]

        ax_raw.imshow(raw_norm, cmap="viridis", aspect="equal",
                      interpolation="nearest")
        ax_raw.axis("off")
        ax_raw.set_title(f"{organ}\n(c={info['contiguity']:.2f})",
                         fontsize=8, fontweight="bold", pad=3)

        ax_map.imshow(labels, cmap=cmap_region, vmin=-0.5,
                      vmax=N_REGIONS - 0.5, aspect="equal",
                      interpolation="nearest")
        ax_map.axis("off")


def draw_panel_b(ax, df):
    """Violin of spatial coherence (contiguity) per organ."""
    top_organs = (df.groupby("organ")["contiguity"]
                    .count()
                    .nlargest(10)
                    .index.tolist())
    data    = [df.loc[df["organ"] == o, "contiguity"].dropna().values for o in top_organs]
    colors  = [ORGAN_PALETTE.get(o, DEFAULT_COLOR) for o in top_organs]
    pos     = list(range(len(top_organs)))

    vp = ax.violinplot(data, positions=pos, showmedians=True,
                       showextrema=False, widths=0.6)
    for body, col in zip(vp["bodies"], colors):
        body.set_facecolor(col)
        body.set_alpha(0.55)
    vp["cmedians"].set_color("#111")
    vp["cmedians"].set_linewidth(1.6)

    ax.set_xticks(pos)
    ax.set_xticklabels(top_organs, rotation=30, ha="right", fontsize=8)
    ax.set_ylabel("Spatial contiguity score", fontsize=9)
    ax.set_title("B   Within-tissue Spatial Coherence by Organ",
                 fontsize=11, fontweight="bold", pad=6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(axis="y", labelsize=8)


def draw_panel_c(ax):
    """UMAP of Stage 1 patch embeddings coloured by organ (computed from current embeddings)."""
    from sklearn.preprocessing import normalize
    import umap as umap_lib

    emb  = np.load(str(EMB_DIR / "resnet_patch_embeddings.npy")).astype(np.float32)
    if emb.ndim > 2:
        emb = emb.reshape(len(emb), -1)
    meta = pd.read_csv(EMB_DIR / "resnet_patch_meta.csv",
                       usecols=["sample_path", "Organism_Part"])

    def _norm(s):
        return {"Kideny": "Kidney", "colon": "Colon"}.get(str(s).strip(), str(s).strip())
    meta["organ"] = meta["Organism_Part"].apply(_norm)

    rng = np.random.default_rng(42)
    N   = min(5_000, len(emb))
    idx = rng.choice(len(emb), N, replace=False)
    emb_sub  = normalize(emb[idx], norm="l2")
    meta_sub = meta.iloc[idx].reset_index(drop=True)

    coords = umap_lib.UMAP(n_components=2, random_state=42,
                            n_neighbors=15, min_dist=0.1,
                            low_memory=True).fit_transform(emb_sub)

    top_organs = meta_sub["organ"].value_counts().head(8).index.tolist()
    palette    = ["#2166ac","#d6604d","#4dac26","#fdae6b","#9970ab",
                  "#1b7837","#e08214","#74add1"]
    color_map  = {o: palette[i] for i, o in enumerate(top_organs)}

    colors = [color_map.get(o, "#cccccc") for o in meta_sub["organ"]]
    ax.scatter(coords[:, 0], coords[:, 1], c=colors,
               s=2, alpha=0.4, linewidths=0, rasterized=True)

    import matplotlib.patches as mpatches
    patches = [mpatches.Patch(color=color_map[o], label=o) for o in top_organs]
    ax.legend(handles=patches, fontsize=6.5, frameon=False,
              loc="lower right", ncol=1, markerscale=1.4)
    ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values():
        sp.set_visible(False)
    ax.set_title("C   Stage 1 Patch Embeddings (UMAP, coloured by organ)",
                 fontsize=11, fontweight="bold", pad=6)


def draw_panel_d(axes, df):
    """Histograms of per-sample PC1-vs-spatial-position Pearson correlation (row/col/combined)."""
    specs = [
        ("pca_r_row",  "Row position",      "#2166ac"),
        ("pca_r_col",  "Column position",   "#d6604d"),
        ("pca_r_mean", "Combined (mean)",   "#4dac26"),
    ]
    for ax, (col, label, color) in zip(axes, specs):
        vals = df[col].dropna().values
        ax.hist(vals, bins=40, color=color, alpha=0.75, edgecolor="white", linewidth=0.3)
        mu, sd = vals.mean(), vals.std()
        ax.axvline(mu, color="#111", linewidth=1.4, linestyle="--")
        ax.text(0.97, 0.95, f"mean = {mu:.3f}\n$\\sigma$ = {sd:.3f}\nn = {len(vals):,}",
                transform=ax.transAxes, ha="right", va="top", fontsize=8)
        ax.set_xlabel(f"Pearson $r$ (PC1 vs. {label.lower()})", fontsize=9)
        ax.set_ylabel("Number of samples", fontsize=9)
        ax.set_title(label, fontsize=10, fontweight="bold", pad=6)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(labelsize=8)


def draw_panel_e(ax, df):
    """Violin of per-sample Spearman rho: channel embedding similarity vs. spatial colocalization."""
    labels = {
        "resnet_only":       "Stage 1",
        "stage2_ch_refined": "Stage 2",
        "mz_only":           "$m/z$-only",
    }
    colors = {
        "resnet_only":       "#74add1",
        "stage2_ch_refined": "#2166ac",
        "mz_only":           "#aaaaaa",
    }
    order = [v for v in ["stage2_ch_refined", "resnet_only", "mz_only"] if v in df["variant"].unique()]
    data  = [df.loc[df["variant"] == v, "spearman_rho"].dropna().values for v in order]

    vp = ax.violinplot(data, positions=range(len(order)), showmedians=True,
                       showextrema=False, widths=0.6)
    for body, v in zip(vp["bodies"], order):
        body.set_facecolor(colors[v])
        body.set_alpha(0.6)
    vp["cmedians"].set_color("#111")
    vp["cmedians"].set_linewidth(1.6)

    for i, (v, d) in enumerate(zip(order, data)):
        mu = d.mean()
        ax.text(i, d.max() + 0.02, f"mean={mu:.3f}", ha="center",
                fontsize=8, color=colors[v], fontweight="bold")

    ax.axhline(0, color="#aaa", lw=0.8, ls="--")
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels([labels[v] for v in order], fontsize=10)
    ax.set_ylabel("Spearman $\\rho$\n(embedding similarity vs. spatial colocalization)", fontsize=9)
    ax.set_title("E   Channel Embedding Similarity Predicts\nSpatial Colocalization",
                 fontsize=11, fontweight="bold", pad=6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(labelsize=8)


def main():
    df_coh = pd.read_csv(PATCH_DIR / "spatial_coherence_all_samples.csv")

    # Panel A — 2 rows × 4 columns: row 0 = raw MSI, row 1 = microregion map
    n_organs = len(ORGANS_A)
    fig, axes = plt.subplots(2, n_organs,
                             figsize=(n_organs * 2.6, 5.5),
                             gridspec_kw={"wspace": 0.04, "hspace": 0.08})
    axes[0, 0].set_ylabel("Raw MSI\n(mean)", fontsize=8, rotation=90, labelpad=4)
    axes[1, 0].set_ylabel("Microregions\n(k=6)", fontsize=8, rotation=90, labelpad=4)
    draw_panel_a(axes)
    save_panel(fig, "figS6_panelA_microregion_maps")
    plt.close(fig)

    # Panel B — spatial coherence violin
    fig, ax = plt.subplots(figsize=(9.0, 5.0))
    draw_panel_b(ax, df_coh)
    save_panel(fig, "figS6_panelB_spatial_coherence")
    plt.close(fig)

    # Panel C — PCA/UMAP scatter
    fig, ax = plt.subplots(figsize=(7.0, 5.5))
    draw_panel_c(ax)
    save_panel(fig, "figS6_panelC_pca_umap_scatter")
    plt.close(fig)

    # Panel D — PC1-vs-position Pearson correlation histograms (row/col/combined)
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.2))
    draw_panel_d(axes, df_coh)
    save_panel(fig, "figS6_panelD_pc1_spatial_correlation")
    plt.close(fig)

    # Panel E — channel colocalization Spearman rho violin
    df_coloc = pd.read_csv(COLOC_DIR / "spearman_per_sample.csv")
    fig, ax = plt.subplots(figsize=(6.5, 5.0))
    draw_panel_e(ax, df_coloc)
    save_panel(fig, "figS6_panelE_colocalization")
    plt.close(fig)

    write_caption()
    print("FigS6 done.")


if __name__ == "__main__":
    main()

